# Perceptron vs Logistic Regression

In [8]:
import pandas as pd  
import numpy as np  
import matplotlib.pyplot as plt  
from sklearn.model_selection import train_test_split 
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
from sklearn.metrics import classification_report, confusion_matrix
%matplotlib inline

import tensorflow.keras as keras
import tensorflow as tf
from tensorflow.keras.utils import plot_model

## AND gate

In [9]:
x_train = np.array([[0.0,0.0],[0.0,1.0],[1.0,0.0],[1.0,1.0]])
y_train = np.array([0.0,0.0,0.0,1.0])

#model = LogisticRegression(solver='liblinear', C=5.0, random_state=0)
#model.fit(x_train,y_train)

model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Dense(x_train.shape[1]))
model.add(tf.keras.layers.Dense(1, activation="sigmoid"))

model.compile(loss='binary_crossentropy', optimizer=keras.optimizers.Adam(learning_rate=0.3, beta_1=0.6, beta_2=0.999, amsgrad=True), metrics=['mse', 'accuracy'])

model.fit(x_train, y_train, epochs=20)

print(model.predict(x_train))
prediction = np.where(model.predict(x_train) < 0.5, 0, 1)
print(prediction)
confusion_matrix(y_train, prediction)

Epoch 1/20
4/4 [==============================] - 0s 23ms/sample - loss: 0.7920 - mean_squared_error: 0.2812 - acc: 0.7500
Epoch 2/20
4/4 [==============================] - 0s 376us/sample - loss: 0.6482 - mean_squared_error: 0.2314 - acc: 0.5000
Epoch 3/20
4/4 [==============================] - 0s 872us/sample - loss: 0.5650 - mean_squared_error: 0.1919 - acc: 0.7500
Epoch 4/20
4/4 [==============================] - 0s 376us/sample - loss: 0.5321 - mean_squared_error: 0.1758 - acc: 0.7500
Epoch 5/20
4/4 [==============================] - 0s 500us/sample - loss: 0.4962 - mean_squared_error: 0.1608 - acc: 0.7500
Epoch 6/20
4/4 [==============================] - 0s 626us/sample - loss: 0.4405 - mean_squared_error: 0.1395 - acc: 0.7500
Epoch 7/20
4/4 [==============================] - 0s 375us/sample - loss: 0.3675 - mean_squared_error: 0.1085 - acc: 0.7500
Epoch 8/20
4/4 [==============================] - 0s 376us/sample - loss: 0.2924 - mean_squared_error: 0.0742 - acc: 1.0000
Epoch 9/2

array([[3, 0],
       [0, 1]], dtype=int64)

## OR gate

In [10]:
x_train = np.array([[0.,0.],[.0,.1],[.1,.0],[.1,.1]])
y_train = np.array([0.,1.,1.,1.])

#model = LogisticRegression(solver='liblinear', C=5.0, random_state=0)
#model.fit(x_train,y_train)

model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Dense(x_train.shape[1]))
model.add(tf.keras.layers.Dense(1, activation="sigmoid"))

model.compile(loss='binary_crossentropy', optimizer=keras.optimizers.Adam(learning_rate=0.3, beta_1=0.6, beta_2=0.999, amsgrad=True), metrics=['mse', 'accuracy'])

model.fit(x_train, y_train, epochs=20)

print(model.predict(x_train))
prediction = np.where(model.predict(x_train) < 0.5, 0, 1)
print(prediction)
confusion_matrix(y_train, prediction) 

Epoch 1/20
4/4 [==============================] - 0s 22ms/sample - loss: 0.7110 - mean_squared_error: 0.2589 - acc: 0.2500
Epoch 2/20
4/4 [==============================] - 0s 503us/sample - loss: 0.5599 - mean_squared_error: 0.1862 - acc: 0.7500
Epoch 3/20
4/4 [==============================] - 0s 503us/sample - loss: 0.5380 - mean_squared_error: 0.1800 - acc: 0.7500
Epoch 4/20
4/4 [==============================] - 0s 376us/sample - loss: 0.5321 - mean_squared_error: 0.1791 - acc: 0.7500
Epoch 5/20
4/4 [==============================] - 0s 251us/sample - loss: 0.5027 - mean_squared_error: 0.1662 - acc: 0.7500
Epoch 6/20
4/4 [==============================] - 0s 627us/sample - loss: 0.4884 - mean_squared_error: 0.1569 - acc: 0.7500
Epoch 7/20
4/4 [==============================] - 0s 376us/sample - loss: 0.4622 - mean_squared_error: 0.1471 - acc: 0.7500
Epoch 8/20
4/4 [==============================] - 0s 501us/sample - loss: 0.4339 - mean_squared_error: 0.1406 - acc: 0.7500
Epoch 9/2

array([[1, 0],
       [0, 3]], dtype=int64)

## NOT gate

In [11]:
x_train = np.array([[.0],[.1]])
y_train = np.array([1.,0.])

model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Dense(x_train.shape[1]))
model.add(tf.keras.layers.Dense(1, activation="sigmoid"))

model.compile(loss='binary_crossentropy', optimizer=keras.optimizers.Adam(learning_rate=0.3, beta_1=0.6, beta_2=0.999, amsgrad=True), metrics=['mse', 'accuracy'])

model.fit(x_train, y_train, epochs=20)

print(model.predict(x_train))
prediction = np.where(model.predict(x_train) < 0.5, 0, 1)
print(prediction)
confusion_matrix(y_train, prediction) 

Epoch 1/20
2/2 [==============================] - 0s 53ms/sample - loss: 0.7331 - mean_squared_error: 0.2699 - acc: 0.0000e+00
Epoch 2/20
2/2 [==============================] - 0s 750us/sample - loss: 0.7710 - mean_squared_error: 0.2862 - acc: 0.5000
Epoch 3/20
2/2 [==============================] - 0s 1ms/sample - loss: 0.7038 - mean_squared_error: 0.2553 - acc: 0.5000
Epoch 4/20
2/2 [==============================] - 0s 2ms/sample - loss: 0.7017 - mean_squared_error: 0.2542 - acc: 0.5000
Epoch 5/20
2/2 [==============================] - 0s 1ms/sample - loss: 0.6982 - mean_squared_error: 0.2525 - acc: 0.5000
Epoch 6/20
2/2 [==============================] - 0s 752us/sample - loss: 0.6891 - mean_squared_error: 0.2480 - acc: 0.5000
Epoch 7/20
2/2 [==============================] - 0s 1ms/sample - loss: 0.6849 - mean_squared_error: 0.2459 - acc: 1.0000
Epoch 8/20
2/2 [==============================] - 0s 501us/sample - loss: 0.6824 - mean_squared_error: 0.2446 - acc: 0.5000
Epoch 9/20
2/

array([[1, 0],
       [0, 1]], dtype=int64)

## NAND gate

In [12]:
x_train = np.array([[0.,0.],[0.,1.],[1.,0.],[.1,1.]])
y_train = np.array([1.,1.,1.,0.])

#model = LogisticRegression(solver='liblinear', C=5.0, random_state=0)
#model.fit(x_train,y_train)

model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Dense(x_train.shape[1]))
model.add(tf.keras.layers.Dense(1, activation="sigmoid"))

model.compile(loss='binary_crossentropy', optimizer=keras.optimizers.Adam(learning_rate=0.3, beta_1=0.6, beta_2=0.999, amsgrad=True), metrics=['mse', 'accuracy'])

model.fit(x_train, y_train, epochs=100)

print(model.predict(x_train))
prediction = np.where(model.predict(x_train) < 0.5, 0, 1)
print(prediction)
confusion_matrix(y_train, prediction) 

Epoch 1/100
4/4 [==============================] - 0s 31ms/sample - loss: 0.7122 - mean_squared_error: 0.2593 - acc: 0.2500
Epoch 2/100
4/4 [==============================] - 0s 385us/sample - loss: 0.5605 - mean_squared_error: 0.1884 - acc: 0.7500
Epoch 3/100
4/4 [==============================] - 0s 251us/sample - loss: 0.5059 - mean_squared_error: 0.1720 - acc: 0.7500
Epoch 4/100
4/4 [==============================] - 0s 376us/sample - loss: 0.4711 - mean_squared_error: 0.1620 - acc: 0.7500
Epoch 5/100
4/4 [==============================] - 0s 375us/sample - loss: 0.4437 - mean_squared_error: 0.1520 - acc: 0.5000
Epoch 6/100
4/4 [==============================] - 0s 623us/sample - loss: 0.4234 - mean_squared_error: 0.1475 - acc: 0.5000
Epoch 7/100
4/4 [==============================] - 0s 509us/sample - loss: 0.4070 - mean_squared_error: 0.1458 - acc: 0.7500
Epoch 8/100
4/4 [==============================] - 0s 376us/sample - loss: 0.3937 - mean_squared_error: 0.1419 - acc: 0.5000
E

Epoch 67/100
4/4 [==============================] - 0s 376us/sample - loss: 0.1654 - mean_squared_error: 0.0375 - acc: 1.0000
Epoch 68/100
4/4 [==============================] - 0s 251us/sample - loss: 0.1634 - mean_squared_error: 0.0402 - acc: 1.0000
Epoch 69/100
4/4 [==============================] - 0s 503us/sample - loss: 0.1582 - mean_squared_error: 0.0368 - acc: 1.0000
Epoch 70/100
4/4 [==============================] - 0s 625us/sample - loss: 0.1531 - mean_squared_error: 0.0359 - acc: 1.0000
Epoch 71/100
4/4 [==============================] - 0s 253us/sample - loss: 0.1496 - mean_squared_error: 0.0332 - acc: 1.0000
Epoch 72/100
4/4 [==============================] - 0s 376us/sample - loss: 0.1501 - mean_squared_error: 0.0359 - acc: 1.0000
Epoch 73/100
4/4 [==============================] - 0s 500us/sample - loss: 0.1582 - mean_squared_error: 0.0386 - acc: 1.0000
Epoch 74/100
4/4 [==============================] - 0s 251us/sample - loss: 0.1877 - mean_squared_error: 0.0599 - acc:

array([[1, 0],
       [0, 3]], dtype=int64)

## XOR gate

In [13]:
x_train = np.array([[0.,0.],[0.,1.],[1.,0.],[1.,1.]])
y_train = np.array([0.,1.,1.,0.])

# HOME WORK :-)